server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "root"
  password: "root"
  dbname: "MicroFaaS"
  sslmode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  max_lifetime: 1800

docker:
  network: "bridge"
  timeout_seconds: 30
